# Generated by Django 5.1.7 on 2025-03-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_customer_alter_employee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
