# Generated by Django 5.1.7 on 2025-03-21 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand_name", models.CharField(max_length=100)),
                ("unit_price", models.IntegerField()),
                ("pack_size", models.IntegerField()),
                ("total_pack", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OUTOFSTOCK", "Out of Stock"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicineapp.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_pack", models.IntegerField()),
                ("purchase_price", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "medicine_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicineapp.medicine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=100)),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=10)),
                ("customer_email", models.CharField(max_length=100)),
                ("medicine_name", models.CharField(max_length=100)),
                ("total_pack", models.IntegerField()),
                ("order_amount", models.IntegerField()),
                ("order_date", models.DateField()),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
